development:
  adapter: postgresql
  encoding: unicode
  database: preserver_development
  pool: 5
  username: root
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: preserver_test
  pool: 5
  username: preserver
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: preserver_production
  pool: 5
  username: preserver
  password:
